name: "Intelligent Download Book"

on:
  workflow_dispatch:
    inputs:
      BOOK_ID:
        description: "BOOK_ID to download"
        required: true
        default: "1"
      DOWNLOAD_MODE:
        description: "Chọn chế độ tải"
        required: true
        default: "per_chapter"
        type: choice
        options:
          - per_chapter
          - single
      THREADS:
        description: "Số luồng tải ảnh đồng thời (max threads)"
        required: true
        default: "8"

env:
  TZ: Asia/Ho_Chi_Minh
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  download:
    runs-on: ubuntu-22.04
    timeout-minutes: 720
    env:
      BOOK_ID: ${{ github.event.inputs.BOOK_ID }}
      DOWNLOAD_MODE: ${{ github.event.inputs.DOWNLOAD_MODE }}
      THREADS: ${{ github.event.inputs.THREADS }}
      BHLNK_EMAIL: ${{ secrets.BHLNK_EMAIL }}
      BHLNK_PASSWORD: ${{ secrets.BHLNK_PASSWORD }}
      PYTHONPATH: ${{ github.workspace }}
      RCLONE_DEST: ${{ secrets.RCLONE_DEST || '1drive:/LSC_Books' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'proplayer1131/sachyhocpdf_downloader-main'
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk jq

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install requests Pillow
          if [ -f requirements.txt ]; then
            grep -v -E 'tkinter|pywin32|win32mica|upx|customtkinter|futures|tqdm' requirements.txt > requirements_linux.txt
            pip install -r requirements_linux.txt
          fi

      - name: Install and configure rclone
        env:
          RCLONE_CONF_CONTENTS: ${{ secrets.RCLONE_CONF }}
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          printf "%s" "$RCLONE_CONF_CONTENTS" > ~/.config/rclone/rclone.conf
          rclone version

      - name: Run Intelligent Download Script
        id: download_script
        run: python -u scripts/download_one.py | tee download.log

      - name: Upload Book and Prepare Info
        id: upload_and_info
        run: |
          set -euo pipefail
          if [ ! -f "folder_name.txt" ]; then
            echo "Không có sách nào được tải về. Bỏ qua."
            echo "DOWNLOADED=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "DOWNLOADED=true" >> $GITHUB_OUTPUT
          
          FOLDER_NAME=$(cat folder_name.txt)
          CLEAN_FOLDER_NAME=$(echo "$FOLDER_NAME" | sed 's/[:*?"<>|]/_/g')
          TARGET="${RCLONE_DEST}/${CLEAN_FOLDER_NAME}"
          
          echo "Uploading '${FOLDER_NAME}' to '${TARGET}'..."
          rclone copy "${FOLDER_NAME}" "${TARGET}" --transfers=8 --checkers=16 --progress
          echo "Tải lên hoàn tất."
          
          INFO_FILE_PATH="${FOLDER_NAME}/book_info.json"
          if [ ! -f "$INFO_FILE_PATH" ]; then
             echo "book_info.json not found! Using fallback values."
             BOOK_TITLE="Không tìm thấy tiêu đề"
             FOLDER_LINK="Không thể tạo link"
          else
             BOOK_TITLE=$(jq -r '.name' "$INFO_FILE_PATH")
             FOLDER_LINK=$(rclone link "${TARGET}" 2>/dev/null || echo "Không thể tạo link")
          fi
          
          echo "BOOK_TITLE<<EOF" >> $GITHUB_OUTPUT
          echo "$BOOK_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "FOLDER_LINK<<EOF" >> $GITHUB_OUTPUT
          echo "$FOLDER_LINK" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Send Download Success Notification
        if: success() && steps.upload_and_info.outputs.DOWNLOADED == 'true'
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ✅ Tải Sách Hoàn Tất (Sách mới)
            📖 Sách: ${{ steps.upload_and_info.outputs.BOOK_TITLE }}
            🆔 ID: ${{ env.BOOK_ID }}
            🔗 Link Thư Mục: [Nhấn vào đây](${{ steps.upload_and_info.outputs.FOLDER_LINK }})

      - name: Send No Update Notification
        if: success() && steps.upload_and_info.outputs.DOWNLOADED == 'false'
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ✅ Kiểm tra hoàn tất.
            Không có sách hoặc chương mới nào cho Book ID: `${{ env.BOOK_ID }}`.

      - name: Send Failure Notification
        if: failure() || cancelled()
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ❌ *Download Failed!*

            *Book ID:* `${{ env.BOOK_ID }}`
            *Status:* `${{ job.status }}`

            Workflow run:
            [${{ github.workflow }}#${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            _See attached log for details._
          document: ./download.log
