name: "Intelligent Download Book"

on:
  workflow_dispatch:
    inputs:
      BOOK_ID:
        description: "BOOK_ID to download"
        required: true
        default: "1"
      DOWNLOAD_MODE:
        description: "Chọn chế độ tải"
        required: true
        default: "per_chapter"
        type: choice
        options:
          - per_chapter
          - single
      THREADS:
        description: "Số luồng tải ảnh đồng thời (max threads)"
        required: true
        default: "64"

env:
  TZ: Asia/Ho_Chi_Minh
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  download:
    runs-on: ubuntu-22.04
    timeout-minutes: 720
    env:
      BOOK_ID: ${{ github.event.inputs.BOOK_ID }}
      DOWNLOAD_MODE: ${{ github.event.inputs.DOWNLOAD_MODE }}
      THREADS: ${{ github.event.inputs.THREADS }}
      BHLNK_EMAIL: ${{ secrets.BHLNK_EMAIL }}
      BHLNK_PASSWORD: ${{ secrets.BHLNK_PASSWORD }}
      PYTHONPATH: ${{ github.workspace }}
      RCLONE_DEST: ${{ secrets.RCLONE_DEST || '1drive:/LSC_Books' }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'proplayer1131/sachyhocpdf_downloader-main'
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk jq

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install requests Pillow psutil
          if [ -f requirements.txt ]; then
            grep -v -E 'tkinter|pywin32|win32mica|upx|customtkinter|futures|tqdm' requirements.txt > requirements_linux.txt
            pip install -r requirements_linux.txt
          fi

      - name: Install and configure rclone
        env:
          RCLONE_CONF_CONTENTS: ${{ secrets.RCLONE_CONF }}
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          printf "%s" "$RCLONE_CONF_CONTENTS" > ~/.config/rclone/rclone.conf
          rclone version

      - name: Run Intelligent Download Script
        id: download_script
        run: python -u scripts/download_one.py | tee download.log

      - name: Read Download Status
        id: status_reader
        run: |
          if [ -f "download_status.txt" ]; then
            STATUS=$(cat download_status.txt)
            echo "Download status: $STATUS"
            echo "DOWNLOAD_STATUS=$STATUS" >> $GITHUB_OUTPUT
          else
            echo "download_status.txt not found. Assuming failure."
            echo "DOWNLOAD_STATUS=UNKNOWN_FAILURE" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload Book and Prepare Info
        id: upload_and_info
        if: |
          steps.status_reader.outputs.DOWNLOAD_STATUS == 'NEW' ||
          steps.status_reader.outputs.DOWNLOAD_STATUS == 'UPDATED' ||
          steps.status_reader.outputs.DOWNLOAD_STATUS == 'SUPPLEMENTED'
        run: |
          set -euo pipefail
          FOLDER_NAME=$(cat folder_name.txt)
          CLEAN_FOLDER_NAME=$(echo "$FOLDER_NAME" | sed 's/[:*?"<>|]/_/g')
          TARGET="${RCLONE_DEST}/${CLEAN_FOLDER_NAME}"
          
          echo "Uploading '${FOLDER_NAME}' to '${TARGET}'..."
          # Logic đã được đơn giản hóa: chỉ cần copy thư mục nguồn
          rclone copy "${FOLDER_NAME}" "${TARGET}" --transfers=8 --checkers=16 --progress
          echo "Tải lên hoàn tất."
          
          INFO_FILE_PATH="${FOLDER_NAME}/book_info.json"
          
          # Logic lấy thông tin sách không đổi và giờ sẽ hoạt động ổn định
          BOOK_TITLE=$(jq -r '.name' "$INFO_FILE_PATH")
          FOLDER_LINK=$(rclone link "${TARGET}" 2>/dev/null || echo "Không thể tạo link")
          
          echo "BOOK_TITLE<<EOF" >> $GITHUB_OUTPUT
          echo "$BOOK_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "FOLDER_LINK<<EOF" >> $GITHUB_OUTPUT
          echo "$FOLDER_LINK" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      # --- Các bước thông báo Telegram (Không thay đổi) ---
      - name: Send Notification (New/Updated/Supplemented)
        if: success() && (steps.status_reader.outputs.DOWNLOAD_STATUS == 'NEW' || steps.status_reader.outputs.DOWNLOAD_STATUS == 'UPDATED' || steps.status_reader.outputs.DOWNLOAD_STATUS == 'SUPPLEMENTED')
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ${{ steps.status_reader.outputs.DOWNLOAD_STATUS == 'NEW' && '✅ Tải Sách Hoàn Tất (Sách mới)' || '' }}${{ steps.status_reader.outputs.DOWNLOAD_STATUS == 'UPDATED' && '🔄 Tải Sách Hoàn Tất (Đã cập nhật)' || '' }}${{ steps.status_reader.outputs.DOWNLOAD_STATUS == 'SUPPLEMENTED' && '➕ Tải Sách Hoàn Tất (Bổ sung file thiếu)' || '' }}
            📖 Sách: ${{ steps.upload_and_info.outputs.BOOK_TITLE }}
            🆔 ID: ${{ env.BOOK_ID }}
            🔗 Link Thư Mục: [Nhấn vào đây](${{ steps.upload_and_info.outputs.FOLDER_LINK }})

      - name: Send Notification (Already Exists)
        if: success() && steps.status_reader.outputs.DOWNLOAD_STATUS == 'EXISTS'
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ℹ️ Kiểm Tra Hoàn Tất (Sách đã có sẵn)
            ID: `${{ env.BOOK_ID }}` - Không có cập nhật mới.

      - name: Send Notification (Not Found)
        if: success() && steps.status_reader.outputs.DOWNLOAD_STATUS == 'NOT_FOUND'
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ⚠️ Quét Thất Bại (Không tồn tại)
            ID: `${{ env.BOOK_ID }}` - Sách không tồn tại hoặc link bị hỏng.
      
      - name: Send Failure Notification
        if: failure() || cancelled() || steps.status_reader.outputs.DOWNLOAD_STATUS == 'DOWNLOAD_FAILED' || steps.status_reader.outputs.DOWNLOAD_STATUS == 'SCRIPT_ERROR'
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ❌ *Download Failed!*
            *Book ID:* `${{ env.BOOK_ID }}`
            *Status:* `${{ job.status }}`
            *Log:* Xem file đính kèm.
          document: ./download.log
