name: OTA Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'URL to the OTA zip file'
        required: true
        default: ''

jobs:
  dump:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - name: Clean 2
        uses: easimon/maximize-build-space@master
        with:
            root-reserve-mb: 512
            swap-size-mb: 1024
            remove-dotnet: "true"
            remove-android: "true"
            remove-haskell: "true"
            
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'proplayer1131/new-dump'
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 uuid-dev liblz4-tool
          pip install poetry
          sed -i 's/README.md/readme.md/g' pyproject.toml
          poetry install
         
      - name: Erofs-utils setup
        run: |
          aria2c -x16 -s16 https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/snapshot/erofs-utils-1.6.tar.gz
          tar -xzf erofs-utils-1.6.tar.gz
          cd erofs-utils-1.6/
          ./autogen.sh
          ./configure
          make
          sudo make install

      - name: Download ROM
        run: |
          aria2c -x16 -s16 -j5 --file-allocation=none --summary-interval=10 "${{ github.event.inputs.ROM_URL }}"

      - name: Process File
        id: process_step
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/dump_and_extract.sh
          ROM_FILENAME=$(basename "${{ github.event.inputs.ROM_URL }}")
          $GITHUB_WORKSPACE/scripts/dump_and_extract.sh "$ROM_FILENAME"
          echo "ota_filename=$ROM_FILENAME" >> $GITHUB_OUTPUT
      
      - name: Configure rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
  
      - name: Upload to OneDrive
        env:
            RCLONE_DEST: "1drive:OTA_DUMPS"
        run: |
            FOLDER_NAME="${{ steps.process_step.outputs.ota_filename }}"
            echo "Uploading 'output' directory..."
            rclone copy output "${RCLONE_DEST}/${FOLDER_NAME}/output" --transfers=8 --checkers=16 --progress
            echo "Uploading 'extracted' directory..."
            rclone copy extracted "${RCLONE_DEST}/${FOLDER_NAME}/extracted" --transfers=8 --checkers=16 --progress