name: OTA Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'URL to the OTA zip file'
        required: true
      CUSTOM_FOLDER_NAME:
        description: 'Optional: Custom folder name for upload. If empty, uses original filename.'
        required: false
        default: ''
      UPLOAD_TARGETS:
        description: 'Select which directories/files to upload.'
        required: true
        type: choice
        options:
          - extracted
          - output
          - both
          - apk_only
        default: 'apk_only'

jobs:
  dump:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    steps:
      - name: Clean
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'proplayer1131/new-dump'
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 uuid-dev liblz4-tool
          pip install poetry
          sed -i 's/README.md/readme.md/g' pyproject.toml
          poetry install

      - name: Erofs-utils setup
        run: |
          aria2c -x16 -s16 https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/snapshot/erofs-utils-1.6.tar.gz
          tar -xzf erofs-utils-1.6.tar.gz
          cd erofs-utils-1.6/
          ./autogen.sh
          ./configure
          make
          sudo make install

      - name: Download ROM
        run: |
          aria2c -x16 -s16 -j5 --file-allocation=none --summary-interval=10 -o rom.zip "${{ github.event.inputs.ROM_URL }}"

      - name: Process File
        id: process_step
        run: |
          chmod +x $GITHUB_WORKSPACE/scripts/dump_and_extract.sh
          $GITHUB_WORKSPACE/scripts/dump_and_extract.sh "rom.zip"
          ORIGINAL_FILENAME=$(basename "${{ github.event.inputs.ROM_URL }}")
          echo "original_filename=$ORIGINAL_FILENAME" >> $GITHUB_OUTPUT

      - name: setup rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF2}}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Clean
        if: github.event.inputs.UPLOAD_TARGETS == 'apk_only'
        run: |
          echo "Selected apk_only. Cleaning 'extracted' directory..."
          find extracted/ -type f ! -name "*.apk" -delete
          find extracted/ -type d -empty -delete
          echo "Cleaning complete. Only APK files and their parent directories remain."

      - name: Upload
        env:
          RCLONE_DEST: "1drive:OTA_DUMPS"
        run: |
          if [[ -n "${{ github.event.inputs.CUSTOM_FOLDER_NAME }}" ]]; then
            FOLDER_NAME="${{ github.event.inputs.CUSTOM_FOLDER_NAME }}"
          else
            FOLDER_NAME="${{ steps.process_step.outputs.original_filename }}"
          fi

          INCLUDE_FLAGS=""
          if [[ "${{ github.event.inputs.UPLOAD_TARGETS }}" == "extracted" ]]; then
            INCLUDE_FLAGS="--include /extracted/**"
            echo "Upload target: extracted"
          elif [[ "${{ github.event.inputs.UPLOAD_TARGETS }}" == "output" ]]; then
            INCLUDE_FLAGS="--include /output/**"
            echo "Upload target: output"
          elif [[ "${{ github.event.inputs.UPLOAD_TARGETS }}" == "both" ]]; then
            INCLUDE_FLAGS="--include /output/** --include /extracted/**"
            echo "Upload target: output and extracted"
          elif [[ "${{ github.event.inputs.UPLOAD_TARGETS }}" == "apk_only" ]]; then
            INCLUDE_FLAGS="--include /extracted/**"
            echo "Upload target: extracted (cleaned to contain only APKs)"
          fi

          echo "Preparing to upload to ${RCLONE_DEST}/${FOLDER_NAME}"
          echo "-----------------------------------------------------"
          echo "Calculating total files and size..."
          rclone size . $INCLUDE_FLAGS
          echo "-----------------------------------------------------"
          echo "Starting upload..."
          rclone copy . "${RCLONE_DEST}/${FOLDER_NAME}" \
            --copy-links \
            $INCLUDE_FLAGS \
            --transfers=8 \
            --checkers=16 \
            --log-level NOTICE \
            --stats-one-line \
            --stats 30s